src/accounts/urls.py
from django.contrib import admin # noqa
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountUpdateView, AccountLogoutView

app_name = 'accounts'
urlpatterns = [

    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    # path('password/', AccountPasswordChangeView.as_view(), name='password'),
    # path('delete/', AccountDeleteView.as_view(), name='profile_delete'),
    # path('leaders/', UsersListView.as_view(), name='leaders'),
    # path('contact_us/', ContactUsView.as_view(), name='contact_us')

]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('shop/', include('shop.urls')),

]

handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'
handler403 = 'core.views.error_403'
handler400 = 'core.views.error_400'

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from django.contrib.auth import password_validation
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from django.utils.translation import gettext_lazy as _


# Create your models here.


class User(AbstractUser):

    class BUYER_STATUS(models.IntegerChoices):
        NEW = 0, "New"
        EXPERIENCED = 1, "experienced"
        REGULAR = 2, "regular"
        VIP = 3, "VIP"

    username_validator = UnicodeUsernameValidator()   
     
    username = models.CharField(
        _('Логин'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("Аккаунт с таким логином уже существует"),
        },
    )
    
    first_name = models.CharField(_('имя'), max_length=150, blank=False)
    last_name = models.CharField(_('фамилия'), max_length=150, blank=False)
    phone_number = PhoneNumberField(_('номер телефона'), region="UA")
    location = models.CharField(_('город'), max_length=30, blank=True)
    birth_date = models.DateField(_('дата рождения'), null=True, blank=True)
    image = models.ImageField(_('аватар'), null=True, default='IMG_3652.JPG', upload_to='avatars/')
    status = models.PositiveIntegerField(choices=BUYER_STATUS.choices, default=BUYER_STATUS.NEW)
    orders = models.ManyToManyField(to='shop.Order', verbose_name='Заказы покупателя', related_name='related_order')


    def save(self, *args, **kwargs):

        super().save(*args, **kwargs)
        if self._password is not None:
            password_validation.password_changed(self._password, self)
            self._password = None

src/accounts/forms.py
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, UsernameField
# from django.forms import forms
from django import forms

from accounts.models import User
from django.utils.translation import gettext_lazy as _


class AccountRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone_number', 'email', 'birth_date']
        labels = {
            'email': ('Электронная почта'),
        }

    error_messages = {
        'password_mismatch': _('The two password fields didn’t match.'),
    }
    password1 = forms.CharField(
        label=_("Пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Подтверждение пароля"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

class AccountUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = User
        fields = ['username', 'first_name', 'last_name', 'phone_number', 'email', 'image', 'birth_date']
        labels = {
            'email': ('Электронная почта'),
        }
    password = None    

class LoginForm(AuthenticationForm):
    username = UsernameField(label=_("Логин"), widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=_("Пароль"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

src/accounts/views.py
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView

from accounts.forms import AccountRegistrationForm, AccountUpdateForm, LoginForm
from accounts.models import User
from shop.mixins import CartMixin
from shop.models import Order, Category, Cart


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, 'User successfully registered')
        return result


class AccountLoginView(LoginView):
    success_url = reverse_lazy('shop:mainpage')
    template_name = 'login.html'
    form_class = LoginForm

    def get_redirect_url(self):
        if self.request.GET.get('next'):
            return self.request.GET.get('next')
        return reverse('shop:mainpage')

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f'{self.request.user} вы вошли в аккаунт')
        return result


class AccountUpdateView(CartMixin, UpdateView):
    model = User
    template_name = 'profile.html'
    success_url = reverse_lazy('accounts:profile')
    form_class = AccountUpdateForm


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.get_object()
        context['customer'] = customer
        context['orders'] = Order.objects.filter(customer=customer).order_by("-id")
        context['categories'] = Category.objects.all()
        return context

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, f" Ваш профиль: {self.request.user} был успешно обновлен")
        return result


class AccountLogoutView(LogoutView):
    template_name = 'logout.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            messages.info(self.request, f'User {self.request.user} has been logged out')
        return super().dispatch(request, *args, **kwargs)

src/accounts/templates/login.html
{% extends 'baseshop.html' %}
{% load crispy_forms_tags %}

{% block title %}
{% endblock %}

{% block content %}
<body class="text-center">
    

    <div class="container justify-content-center">
        <a class="btn btn-primary" href="{% url 'accounts:registration' %}" role="button">Регистрация</a>
        <p class='mt-3'>Войдите в аккаунт при помощи <br> вашего логина и пароля</p>
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <form method='post' class="form-control" style="margin-top:30px;">
                        {% csrf_token %}
                        {{ form|crispy }}

                    <button type="submit" class="btn btn-primary btn-lg" style="margin-top:10px">Войти</button>

                </form>
            </div>    
        </div>
    </div>
</body>    
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% block greetings %}
    
{% endblock %}

{% block content %}
    <h3 class="text"  style="text-align:center; color:red;">Вы вышли из профиля</h1>
    <div class="d-grid gap-2 col-4 mx-auto">
        
        <a href="{% url 'index' %}" class="btn btn-primary" type="button">На главную</a>
    </div>    
{% endblock %}

src/accounts/templates/profile.html
{% extends 'baseshop.html' %}
{% load crispy_forms_tags %}
{% block title %}
{% endblock %}

{% block content %}
    
    
    <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}    
            {% endif %}    
        <h1 class="display-2    "  style="text-align:center; color:red;">Ваш профиль</h1>
        <div class="row justify-content-center">
            <div class="col-md-6 offset-md-3">
                <div class="media">
                    <div class="img-circle.vert">
                        <img class="rounded-circle p-1 m-1" width="200" height="200"  src="{{ user.image.url }}">

                    </div><a class="btn btn-danger" href="{% url 'accounts:logout' %}" role="button">Выйти</a>
                    <div class="media-body  p-3 m-3">
                        <h2 class="account-heading">{{ user.username }}</h2>
                        <h3 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h3>
                        <p class="text-secondary">{{ user.email }}</p>

                    </div>
                </div>
            </div>    
        </div>        
             <div class="container">
                <div class="row">
                            <button class="btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#orders" aria-expanded="false" aria-controls="collapseExample">
                                <h5 class="account-heading text-center">Ваши заказы</h5>
                            </button> 
                            <div class="collapse" id="orders">
                                <div class="card card-body">
                                    {% if not orders.count %}
                                        <h3>У вас еще нет заказов</h3>
                                    {% else %}
                                        <div class="table-responsive-lg">
                                            <table class="table table-striped table-sm" style="text-align: center">
                                                <thead>
                                                    <th scope="col">Номер</th>
                                                    <th scope="col">Статус</th>
                                                    <th scope="col">Сумма</th>
                                                    <th scope="col">Товар</th>
                                                    <th scope="col">#</th>
                                                </thead>
                                                <tbody>
                                                    {% for order in orders %}
                                                        <tr>
                                                            <th scope="row">{{ order.id }}</th>
                                                            <td>{{ order.get_status_display }}</td>
                                                            <td>{{ order.get_final_price }} грн</td>
                                                            <td>
                                                                <ul>
                                                                    {% for item in order.cart.products.all %}
                                                                        <li>{{ item.product.full_name }} x {{ item.qty }}</li>
                                                                    {% endfor %}
                                                                </ul>
                                                            </td>
                                                            <td>
                                                                <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal-{{ order.id }}">
                                                                Дополнительно
                                                                </button>
                                                                <!-- Modal -->
                                                            <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                                <div class="modal-dialog modal-dialog-scrollable modal-lg">
                                                                    <div class="modal-content">
                                                                    <div class="modal-header">
                                                                        <h5 class="modal-title" id="{{ order.id }}">Ваш заказ</h5>

                                                                    </div>
                                                                    <div class="modal-body">
                                                                        <h4 class="text-center">Товар</h4>
                                                                        <table class="table">
                                                                            <head>
                                                                                <th scope="col">Наименование</th>
                                                                                <th scope="col">Цена</th>
                                                                                <th scope="col">Количество</th>
                                                                                <th scope="col">Общая цена</th>
                                                                            </head>
                                                                            <tbody>
                                                                                {% for item in order.cart.products.all %}
                                                                                    <tr>
                                                                                        <th scope="row">{{ item.product.full_name }}<img src="{{ item.product.image.url }}" width="80" height="80" class="rounded mx-auto d-block "></th>
                                                                                        <td><strong>{{ item.product.price }}</strong> грн.</td>
                                                                                        <td scope="row" style="text-align:center">{{ item.qty }}</td>
                                                                                        <td>{{ item.final_price }} грн.</td>
                                                                                    </tr>
                                                                                {% endfor %}
                                                                                    <tr>
                                                                                        <td colspan="1"></td>
                                                                                        <td>Всего наименований</td>
                                                                                        <td style="text-align:center">{{ order.cart.total_products }}</td>
                                                                                        <td><strong>{{ order.cart.final_price }} грн.</strong></td>
                                                                                    </tr>
                                                                            </tbody>
                                                                        </table>
                                                                        <hr>
                                                                        <h4 class="text-center">Дополнительная информация</h4>
                                                                        <p>Имя: <strong>{{ order.first_name }}</strong></p>
                                                                        <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                                                                        <p>Телефон: <strong>{{ order.phone }}</strong></p>
                                                                    </div>
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                                                    </div>
                                                                    </div>
                                                                </div>
                                                                </div>
                                                            </td>
                                                        </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    {% endif %}
                                </div>            
                            </div>        
                        
                        <h3 class="mt-2 text-center"> Изменить данные </h3>
                        <form method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                        {{ form|crispy }}

                            <input class="btn btn-success btn-lg mt-2" type="submit" value="Save">

                        </form>    
                </div>            
    </div>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}

{% endblock %}

                {% block header %}

                {% endblock %}

                {% block content %}
    <h1 class="display-3"  style="text-align:center; color:red;">Создайте аккаунт</h1>

    <div class="container-md">

            <form method='post' class="form-control bg-light" style="margin-top:30px;">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-success btn-lg" style="margin-top:10px">Создать</button>

            </form>

    </div>
                {% endblock %}