src/accounts/urls.py
from django.contrib import admin # noqa
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountUpdateView, AccountLogoutView

app_name = 'accounts'
urlpatterns = [

    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    # path('password/', AccountPasswordChangeView.as_view(), name='password'),
    # path('delete/', AccountDeleteView.as_view(), name='profile_delete'),
    # path('leaders/', UsersListView.as_view(), name='leaders'),
    # path('contact_us/', ContactUsView.as_view(), name='contact_us')

]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('shop/', include('shop.urls')),

]

handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'
handler403 = 'core.views.error_403'
handler400 = 'core.views.error_400'

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf.urls.static import static

from shop.views import BaseShopView, CategoryDetailView, CartView, AddToCartView, DeleteFromCartView, ChangeQTYView, \
    ProductDetailView, CheckoutView, MakeOrderView, BrandDetailView

app_name = 'shop'

urlpatterns = [

    path('', BaseShopView.as_view(), name='mainpage'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('brand/<str:slug>/', BrandDetailView.as_view(), name='brand_detail'),

    path('products/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),

    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order')
]

src/shop/models.py
from django.db import models
from PIL import Image

from accounts.models import User

from django.utils import timezone
from django.urls import reverse
from decimal import *
from phonenumber_field.modelfields import PhoneNumberField


class Category(models.Model):
    # class CATEGORY_CHOICES(models.IntegerChoices):
    #     PIGMENTS = 0, "Pigments"
    #     CARTRIDGES = 1, "Cartridges"
    #     CAPS = 2, "Caps"
    #     ANASTESIA = 3, "Anastesia"

    # title = models.PositiveIntegerField(choices=CATEGORY_CHOICES.choices, verbose_name='Название категории')
    title = models.CharField(max_length=155, verbose_name='Название категории')
    slug = models.SlugField(unique=True)
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение', upload_to='covers')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:category_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        super(Category, self).save(*args, **kwargs)
        if self.image:
            img = Image.open(self.image.path)

            if img.height > 600 or img.width > 600:
                output_size = (600, 600)
                img.thumbnail(output_size)
                img.save(self.image.path)


class Brand(models.Model):
    category = models.ForeignKey(Category, verbose_name='Категория', related_name="brands", on_delete=models.CASCADE)
    title = models.CharField(max_length=155, verbose_name='Название')
    slug = models.SlugField(unique=True)
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение', upload_to='covers')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:brand_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        super(Brand, self).save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 600 or img.width > 600:
                output_size = (600, 600)
                img.thumbnail(output_size)
                img.save(self.image.path)


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name='Категория', related_name='category_products',
                                 on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, verbose_name='Производитель', related_name="products", on_delete=models.CASCADE)
    name = models.CharField(max_length=155, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(null=True, blank=True, verbose_name='Изображение', upload_to='covers')
    description = models.TextField(max_length=1024, verbose_name='Описание', null=True, blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена', null=True)
    count = models.IntegerField(verbose_name='Количетво', blank=True, null=True)
    discount = models.IntegerField(verbose_name="Скидка", default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Стоимость со скидкой')

    def full_name(self):
        return f'{self.brand.title} {self.name}'

    def _get_final_price(self):
        if self.discount:
            self.final_price = Decimal(self.price - (self.price / 100) * self.discount).quantize(Decimal('1.11'),
                                                                                                 rounding=ROUND_UP)
        else:
            self.final_price = self.price
        return self.final_price

    def get_absolute_url(self):
        return reverse('shop:product_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.brand.title} {self.name}'

    def save(self, *args, **kwargs):
        self.final_price = self._get_final_price()
        super(Product, self).save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            if img.height > 600 or img.width > 600:
                output_size = (600, 600)
                img.thumbnail(output_size)
                img.save(self.image.path)


class CartProduct(models.Model):
    buyer = models.ForeignKey(User, verbose_name='Покупатель', related_name='cartproduct_buyer',
                              on_delete=models.CASCADE, null=True, default=3)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', related_name='cartproduct_cart', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name="Товар", related_name='cartproduct_product',
                                on_delete=models.CASCADE)
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='Общая цена', null=True)

    def __str__(self):
        return f'Cart product: {self.product.brand.title} {self.product.name}'

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.product.final_price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey(User, verbose_name='Владелец', related_name='cart_owner', on_delete=models.CASCADE,
                              default=3)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='cart_products')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена', default=0, null=True)
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        self.total_products = CartProduct.objects.filter(cart_id=self.id).count()
        self.final_price = sum(obj.final_price for obj in CartProduct.objects.filter(cart_id=self.id))
        super().save(*args, **kwargs)


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(User, verbose_name='Покупатель', related_name='related_orders',
                                 on_delete=models.CASCADE, null=True, default=3)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = PhoneNumberField(verbose_name='Номер телефона',  region="UA")
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказ',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', auto_now=True, null=True)

    def get_final_price(self):
        final_price = self.cart.final_price
        return final_price

    def __str__(self):
        return str(self.id)


        

src/shop/forms.py
from django import forms

from shop.models import Order


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['order_date'].label = 'Дата получения заказа'

    # order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'comment'
        )

src/shop/views.py
from django.shortcuts import render
from django.db import transaction
from django.views.decorators.csrf import csrf_exempt


from django.views.generic import DetailView, View
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.http import HttpResponseRedirect

from accounts.models import User
from shop.forms import OrderForm
from shop.mixins import CartMixin
from shop.models import Category, Product, Brand, CartProduct
from shop.utils import recalc_cart


class BaseShopView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        products = Product.objects.all
        context = {
            'categories': categories,
            'products': products,
            'cart': self.cart
        }
        return render(request, 'baseshop.html', context)


class CategoryDetailView(CartMixin, DetailView):

    model = Category
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'

    def get_object(self):
        slug = self.kwargs.get('slug')
        return self.model.objects.get(slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(object_list=self.get_queryset(), **kwargs)
        context['brand_list'] = Brand.objects.filter(
            category=self.get_object()
        )
        context['categories'] = Category.objects.all()
        context['products'] = Product.objects.filter(category=self.get_object())
        context['cart'] = self.cart
        return context

    def get_queryset(self):
        return Brand.objects.filter(
            category=self.get_object())


class BrandDetailView(CartMixin, DetailView):

    model = Brand
    context_object_name = 'brand'
    template_name = 'brand_detail.html'
    slug_url_kwarg = 'slug'

    def get_object(self):
        slug = self.kwargs.get('slug')
        return self.model.objects.get(slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['brands'] = Brand.objects.filter(category=self.object.category_id)
        context['categories'] = Category.objects.all()

        context['products'] = Product.objects.filter(brand=self.get_object())
        context['cart'] = self.cart
        return context

    def get_queryset(self):
        return Product.objects.filter(
            brand=self.get_object())


class ProductDetailView(CartMixin, DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'

    def get_object(self, queryset=None):
        slug = self.kwargs.get('slug')
        return self.model.objects.get(slug=slug)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['cart'] = self.cart
        return context


class AddToCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        product = Product.objects.get(slug=product_slug)
        cart_product, created = CartProduct.objects.get_or_create(
            buyer=self.cart.owner, cart=self.cart, product=product
        )
        if created:
            self.cart.products.add(cart_product)
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар добавлен")
        return HttpResponseRedirect('/shop/')


class DeleteFromCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        product = Product.objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            buyer=self.cart.owner, cart=self.cart, product=product
        )
        self.cart.products.remove(cart_product)
        cart_product.delete()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар удален")
        return HttpResponseRedirect('/shop/cart/')


class ChangeQTYView(CartMixin, View):

    def post(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        product = Product.objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            buyer=self.cart.owner, cart=self.cart, product=product
        )
        qty = int(request.POST.get('qty'))
        cart_product.qty = qty
        cart_product.save()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Кол-во успешно изменено")
        return HttpResponseRedirect('/shop/cart/')


class CheckoutView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        form = OrderForm(request.POST or None)
        context = {
            'cart': self.cart,
            'categories': categories,
            'form': form
        }
        return render(request, 'checkout.html', context)


class CartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        context = {
            'cart': self.cart,
            'categories': categories
        }
        return render(request, 'cart.html', context)


class MakeOrderView(CartMixin, View):

    @transaction.atomic
    @csrf_exempt
    def post(self, request, *args, **kwargs):

        form = OrderForm(request.POST or None)
        customer = self.cart.owner
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone = form.cleaned_data['phone']
            new_order.address = form.cleaned_data['address']
            new_order.buying_type = form.cleaned_data['buying_type']
            # new_order.order_date = form.cleaned_data['order_date']
            new_order.comment = form.cleaned_data['comment']
            new_order.save()
            self.cart.in_order = True
            self.cart.save()
            new_order.cart = self.cart
            new_order.save()
            customer.orders.add(new_order)
            messages.add_message(request, messages.INFO, 'Спасибо за заказ! Менеджер с Вами свяжется')
            return HttpResponseRedirect('/shop/')
        return HttpResponseRedirect('/shop/checkout/')

src/shop/templates/baseshop.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">    <link rel="stylesheet" href="{% static 'shop/css/style.css' %}">

{% block title %}
        <title>Shop</title>
{% endblock %}

</head>
{% block header %}
<header id="header" class="fixed-top ">
  

    
        
    <nav class="navbar fixed-top navbar-light bg-light">  
      <div class="container justify-content-between">
        <a class="navbar-brand" href="{% url 'shop:mainpage' %}"><h5>Symmetria-Shop</h5></a>
        {%  if not user.is_authenticated %}
          <a href="{% url 'accounts:login' %}"><img  width="35" height="35" src="{% static 'core/img/assignment.svg' %}" class="d-inline-block align-top" loading="lazy" alt=""></a>
          

        {% endif %}
        {%  if user.is_superuser %}

          <a class="nav-link" href="/admin/">Admin</a>

        {%  endif %}

        {%  if user.is_authenticated %}        
          
            <a class="nav-link" href="{% url 'accounts:profile' %}"><img alt="Profile pic" width="35" height="35" class="rounded-circle d-inline-block align-top" src="{{ user.image.url }}"></a>
          
                
        {% endif %}
        
        <a class="nav-link" href="{% url 'shop:cart' %}"><img width="25" height="25" src="{% static 'core/img/shopping-cart.png' %}" class="d-inline-block align-top" loading="lazy" alt=""><span class="badge rounded-pill bg-danger">{{ cart.products.count }}</span></a>   
        
      </div>
    </nav>      
</header>  
{% endblock %}
<body style="margin-top: 100px;">
    

{% block content %}


     <div class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
        {% endif %}
     </div>

    <div class="container-xl">

        <div class="row">
           <!-- Категории -->
            <div class="col-lg-3 mt-3">
              <div class="d-grid gap-2">
                <button class="btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#category" aria-expanded="true" aria-controls="collapseExample">
                  <p class="h5"><em>Категории</em></p>
                </button>
              </div>  
              <div class="collapse show" id="category">
                <div class="card card-body">
                  <ul class="list-group list-group-flush">
                    {% for category in categories %}
                        <a class="btn btn-outline-secondary btn-lg btn-block mt-3" href="{% url 'shop:category_detail' slug=category.slug %}">{{ category.title }}
                            <img alt="category pic" width="50" height="50" class="rounded-circle" src="{{ category.image.url }}"></a>
                    {% endfor %}
                  </ul>
                </div>
              </div> 
            </div> 
              <!-- Товары -->
             <div class="col-lg-9 mt-3">
              <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{% static 'shop/img/buldog-cartridges.jpg' %}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'shop/img/buldog-cartridges.jpg' %}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'shop/img/buldog-cartridges.jpg' %}" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
                    <h5 class="text-center">Товары</h5>
                    <div class="row mt-3">
                          {% for product in products %}
                              <div class="col-6 col-md-3 mt-3">
                                <div class="card text-center">{% if product.discount %}<span class="badge bg-danger">скидка {{ product.discount }} %</span>{% endif %}

                                  <a href="{{ product.get_absolute_url }}"><img alt="brand pic" width="100" height="200" class="card-img-top" src="{{ product.image.url }}" alt=""></a>
                                  <div class="card-body bg-light">
                                    <h6 class="card-title">{{ product.full_name }}</h6>
                                    
                                    {% if product.discount %}
                                      
                                        <div class="d-flex justify-content-center">
                                          <p style="text-decoration: line-through; color: red;">{{ product.price }}</p><h6><span style="size: 14px;"> {{ product.final_price }} грн.</span></h6>
                                        </div>
                                       
                                    {% else %}
                                        <h6><span style="size: 14px;">{{ product.final_price }} грн.</span></h6>

                                    {% endif %}
                                    <a href="{% url 'shop:add_to_cart' slug=product.slug %}">
                                        <button class="btn btn-success">Добавить в корзину</button>
                                    </a>
                                  </div>
                                </div>
                              </div>
                          {% endfor %}
                    </div>
             </div>
      </div>
    </div>
{% endblock %}




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
</html>

</body>

src/shop/templates/brand_detail.html
{% extends 'baseshop.html' %}
{% load static %}




{% block content %}


     <div class="container">

        <nav aria-label="breadcrumb" class="mt-3">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'shop:mainpage' %}">Главная</a></li>
            <li class="breadcrumb-item"><a href="{{ brand.get_absolute_url }}">{{ brand.title }}</a></li>
         </ol>
        </nav>

          <div class="col-lg-3 mt-5">
            <ul class="list-group">
              {% for brand in brands %}
                <a href="{{ brand.get_absolute_url }}"><li class="list-group-item" style="text-align:center">{{ brand.title }}
                    <img alt="brand pic" width="50" height="50" class="rounded-circle" src="{{ brand.image.url }}">
                </li></a>
              {% endfor %}
            </ul>
          </div>

         <div class="row mt-5">
              {% for product in products %}
                  <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100">
                      <a href="{{ product.get_absolute_url }}"><img alt="brand pic" weight="100" height="100" class="img-fluid" src="{{ product.image.url }}" alt=""></a>
                      <div class="card-body">
                        <h4 class="card-title">
                          <a href="{{ product.get_absolute_url }}">{{ product.full_name }}</a>
                        </h4>
                        {% if product.discount %}
                            <h6 style="color: red">скидка {{ product.discount }} %</h6>

                            <h6>старая цена: {{ product.price }} грн.</h6>
                            <h5 style="color: red">новая цена: {{ product.final_price }} грн.</h5>
                        {% else %}
                            <h5>цена: {{ product.final_price }} грн.</h5>

                        {% endif %}
                        <a href="{% url 'shop:add_to_cart' slug=product.slug %}">
                            <button class="btn btn-danger">Добавить в корзину</button>
                        </a>

                      </div>
                    </div>
                  </div>
              {% endfor %}
         </div>
     </div>


{% endblock %}

src/shop/templates/cart.html
{% extends 'baseshop.html' %}

{% block content %}
{% if messages %}
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>{{ message }}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
  {% endif %}
  <div class="container">
    <h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %}пуста</h3>
    <div class="row">
      
        <a class="btn btn-primary" href="{% url 'shop:mainpage' %}" role="button">На главную</a>
      
    </div>
  </div>    
    {% endif %}
    

    {% if cart.products.count %}
  <div class="container">
    <div class="table-responsive-sm">
          <table class="table table-striped table-sm" style="text-align: center;">
            <thead>
              <tr>
                <th scope="col">Наименование</th>
                <th scope="col">Цена</th>
                <th scope="col">Скидка</th>
                <th scope="col">Кол-во</th>
                <th scope="col">Общая цена</th>
                <th scope="col">Действие</th>
              </tr>
            </thead>
            <tbody>
              {% for item in cart.products.all %}
                  <tr>
                    <td scope="row" >{{ item.product.full_name }}
                      <img src="{{ item.product.image.url }}" width="80" height="80" class="rounded mx-auto d-block ">
                    </td>
                    <td>{{ item.product.price }} грн./шт</td>
                    <td style="color: red">{{ item.product.discount }} %</td>


                    <td>
                      <form action="{% url 'shop:change_qty' slug=item.product.slug %}" method="POST">
                        {% csrf_token %}
                        <input type="number" class="form-control" name="qty" style="width: 60px;" min="1" value="{{ item.qty }}">
                        <br>
                        <input type="submit" class="btn btn-sm btn-primary" value="Изменить кол-во">
                      </form>
                    </td>
                      <td>{{ item.final_price }} грн.</td>
                    <td>
                      <a href="{% url 'shop:delete_from_cart' slug=item.product.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
                    </td>
                  </tr>
              {% endfor %}
                  <tr>
                    <td colspan="1"></td>
                    <td><strong>Итого:</strong></td>
                    <td>{{ cart.total_products }} наименований </td>
                    <td> на сумму: </td>
                    <td><strong>{{ cart.final_price }} грн.</strong></td>
                    <td><a href="{% url 'shop:checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a></td>
                  </tr>
            </tbody>
          </table>
    </div>  
  </div>
{% endif %}

{% endblock content %}