src/accounts/urls.py
from django.contrib import admin # noqa
from django.urls import path

from accounts.views import AccountRegistrationView, AccountLoginView, AccountUpdateView, AccountLogoutView

app_name = 'accounts'
urlpatterns = [

    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    # path('password/', AccountPasswordChangeView.as_view(), name='password'),
    # path('delete/', AccountDeleteView.as_view(), name='profile_delete'),
    # path('leaders/', UsersListView.as_view(), name='leaders'),
    # path('contact_us/', ContactUsView.as_view(), name='contact_us')

]

src/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('services/', include('services.urls')),
    path('shop/', include('shop.urls')),

]

handler404 = 'core.views.error_404'
# handler500 = 'core.views.error_500'
handler403 = 'core.views.error_403'
handler400 = 'core.views.error_400'

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/services/urls.py
from django.contrib import admin  # noqa
from django.urls import path
# from django.views.generic import TemplateView

from services.views import *

app_name = 'services'
urlpatterns = [

    path('', BaseServiceView.as_view(), name='base_services'),
    path('services/<str:slug>/', ServiceDetailView.as_view(), name='service_detail'),

]

src/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf.urls.static import static

from shop.views import BaseShopView, CategoryDetailView, CartView, AddToCartView, DeleteFromCartView, ChangeQTYView, \
    ProductDetailView, CheckoutView, MakeOrderView, BrandDetailView

app_name = 'shop'

urlpatterns = [

    path('', BaseShopView.as_view(), name='mainpage'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('brand/<str:slug>/', BrandDetailView.as_view(), name='brand_detail'),

    path('products/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),

    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order')
]

src/core/models.py
from django.db import models

# Create your models here.

src/core/views.py
from django.shortcuts import render


def error_404(request, exception):
    data = {}
    return render(request,
                  template_name='404.html',
                  context=data)


# def error_500(exception):
#     data = {}
#     return render(template_name='500.html',
#                   context=data)


def error_403(request, exception):
    data = {}
    return render(request,
                  template_name='403.html',
                  context=data)


def error_400(request, exception):
    data = {}
    return render(request,
                  template_name='400.html',
                  context=data)

src/core/templates/base.html
{% load static %}

<!doctype html>
<html lang="ru">
  <head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">        <title>Base</title>


</head>
                {% block header %}

                {% endblock %}
<body>
    <div class="container-fluid bg-dark" >
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
              <div class="container-fluid " style="justify-content: center;">
                <a class="navbar-brand" href="{% url 'index' %}"><h1>Symmetria-house</h1></a>


                <div class="navbar-expand justify-content-center" id="navbarprofilecontent">
                    <ul class="navbar-nav">



                            {%  if user.is_authenticated %}

                                <li class="nav-item">
                                    <img alt="Profile pic" width="35" height="35" class="rounded-circle" src="{{ user.image.url }}">
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{ user.username }})</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link" style="color: crimson;" href="{% url 'accounts:logout' %}">Выйти</a>
                                 </li>



                            {% else %}
                                  <li class="nav-item">
                                    <a class="nav-link" href="{% url 'accounts:registration' %}">Регистрация</a>
                                  </li>

                                  <li class="nav-item">
                                    <a class="nav-link" href="{% url 'accounts:login' %}">Авторизация</a>
                                  </li>
                            {% endif %}
                    </ul>
                </div>
              </div>
        </nav>
    </div>
                {% block content %}
                {% endblock %}



<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script></body>
</html>

src/core/templates/index.html
{% extends 'base.html' %}
{% load static %}




{% block content %}
    <div class="contaiber-fluid bg-dark" >

        <div class="container mt-3" style=border-width:2px;">
            <h1 style="text-align:center; font-size:300%; color:white;">WELCOME TO Symmetria!!!</h1>
             <div class="row mt-5 justify-content-center">
                <div class="col-6 col-md-3 mb-4">
                        <a href="{% url 'services:base_services' %}"><div class="card h-100">
                          <img alt="brand pic" width="100%" height="100%" class="card-img" src= "{% static 'services/img/PM.JPG' %}">

                        </div></a>
                </div>
                <div class="col-6 col-md-3 mb-4">
                        <a href="{% url 'shop:mainpage' %}"><div class="card h-100">
                            <img alt="brand pic" width="100%" height="100%" class="card-img" src= "{% static 'core/img/shop.jpeg' %}">

                        </div></a>
                </div>
             </div>
        </div>
    </div>

{% endblock %}